name: Update Nft Status

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --silent --no-progress --non-interactive --frozen-lockfile
      - run: yarn workspace @getalpha-scraper/update-nft-stats start
        env:
          DB_URI: ${{ secrets.DB_URI }}
          OPENSEA_API: ${{ secrets.OPENSEA_API }}

